name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - .github/workflows/release.yml
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Metanorma
        run: |
          sudo apt-get update
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash
          sudo chown -R $USER:$(id -gn $USER) $HOME/.config

      - name: Install bundler
        run: |
          sudo gem install bundler

      - name: Install yq
        run: |
          sudo snap install yq
          # echo "::add-path::/snap/bin"
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          make test

      - name: Build
        run: |
          make all

      - name: Test against DTD NISO
        run: |
          make mn2stsDTD_NISO

      - name: Test against DTD ISO
        run: |
          make mn2stsDTD_ISO

      - name: Compile output
        run: |
          make publish

      - uses: actions/upload-artifact@master
        with:
          name: published-ubuntu
          path: published


  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published-ubuntu
        path: published

    - name: GitHub Pages action
      uses: docker://peaceiris/gh-pages:v2
      with:
        emptyCommits: false
        forceOrphan: true
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./published
