name: windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup prerequisites
        run: choco install --no-progress make gnuwin32-coreutils.install curl

      - name: Use Metanorma
        shell: pwsh
        run: |
          cinst --no-progress -y metanorma
      - name: Install yq
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_windows_amd64.exe " -OutFile ".\yq.exe"
      - name: Install bundler
        run: |
          gem install bundler
      - name: Metanorma compile
        run: |
          make clean all

      - name: Run tests
        run: |
          make test

      - name: Build
        run: |
          make all

      - name: Test against DTD NISO
        run: |
          make mn2stsDTD_NISO

      - name: Test against DTD ISO
        run: |
          make mn2stsDTD_ISO

      - name: Compile output
        run: |
          make publish
