name: windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup prerequisites
        run: choco install --no-progress make gnuwin32-coreutils.install

      - uses: actions/checkout@master

      - name: Run tests
        run: |
          make test SHELL=cmd

      - name: Build
        run: |
          make all SHELL=cmd

      - name: Test against DTD NISO
        run: |
          make mn2stsDTD_NISO SHELL=cmd

      - name: Test against DTD ISO
        run: |
          make mn2stsDTD_ISO SHELL=cmd

      - name: Compile output
        run: |
          make publish SHELL=cmd
